<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transfer Letter</title>
    <style>
        @page {
            size: A4;
        }

        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 100%;
            max-width: 20cm;
            padding: 10px;
            margin: auto;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }

        .header h1 {
            font-size: 28px;
            margin: 5px 0;
            color: red;
        }

        .content {
            font-size: 16px;
            color: #444;
            margin-bottom: 30px;
        }

        .footer {
            margin-top: 40px;
            font-size: 14px;
            text-align: left;
            color: #777;
            border-top: 1px solid #ccc;
            padding-top: 10px;
        }

        .signature {
            margin-top: 40px;
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            font-size: 16px;
        }

        .signature img {
            width: 150px;
            margin-top: 10px;
        }

        .highlight {
            font-weight: bold;
            color: #000;
        }

        .system-info {
            margin-top: 30px;
            font-size: 12px;
            text-align: center;
            color: #999;
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="header">
            <h1>Official Rotation Letter</h1>
        </div>

        <div class="content">
            <p>Dear <span class="highlight">{{ $employeeName }}</span>,</p>
            <p>You have been assigned a rotation to the <span class="highlight">{{ $newBranch }}</span> branch as
                a
                <span class="highlight">{{ $job }}</span>. Your rotation period starts on <span
                    class="highlight">{{ $startDate }}</span> and ends on <span
                    class="highlight">{{ $rotationEndDate }}</span>.
            </p>
            <p>Previously, you were working at the <span class="highlight">{{ $oldBranch }}</span> branch. This
                rotation is to help enhance cross-functional experience and efficiency.</p>
            <p>Please ensure a smooth transition and continue your commitment to excellence.</p>
        </div>

        <div class="signature">
            <p>Best regards,</p>
            <p><strong>Tania Khaddaj</strong></p>
            <p>HR Manager</p>
            <img src="{{ public_path('signatures/tania-signature.png') }}" alt="Tania Khaddaj Signature">
        </div>

        <div class="footer">
            <p>CC: Malik Barakat</p>
            <p>CC: Hassan Nasserdine</p>
            <p>CC: Wael Chamandi</p>
        </div>

        <div class="system-info">
            <p>This document was automatically generated by the HR System.</p>
            <p>Developed by <strong>Shadi Farhat</strong> | IT Manager</p>
        </div>
    </div>

</body>

</html>
