<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promotion Letter</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 50px;
            padding: 40px;
            border: 2px solid #ddd;
            border-radius: 10px;
            max-width: 700px;
            margin: auto;
            position: relative;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #007bff;
            padding-bottom: 15px;
        }

        .header h1 {
            font-size: 22px;
            color: #007bff;
            text-transform: uppercase;
            font-weight: bold;
            margin: 0;
        }

        .header p {
            font-size: 14px;
            color: #555;
            margin: 5px 0;
        }

        .content {
            margin-top: 30px;
            font-size: 16px;
            line-height: 1.6;
            color: #333;
        }

        .content p {
            margin-bottom: 10px;
        }

        .highlight {
            font-weight: bold;
            color: #007bff;
        }

        .footer {
            margin-top: 40px;
            padding-top: 20px;
            font-size: 14px;
            color: #666;
            border-top: 2px solid #ddd;
        }

        .signature {
            margin-top: 40px;
            font-size: 16px;
            font-weight: bold;
        }

        /* ✅ Creative Handwritten-Like Signature */
        .signature img {
            width: 180px;
            /* Adjust size */
            height: auto;
            margin-top: 10px;
        }

        .cc {
            font-size: 12px;
            margin-top: 30px;
            color: #888;
        }

        .date {
            text-align: right;
            font-size: 14px;
            font-weight: bold;
            color: #444;
        }

        /* ✅ Developer Credit Section */
        .credits {
            position: absolute;
            bottom: -30px;
            left: 0;
            right: 0;
            font-size: 12px;
            text-align: center;
            color: #888;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            margin-top: 40px;
        }
    </style>
</head>

<body>

    @php
        $month = date('F', strtotime('2025-02-01')); // February
        $year = date('Y', strtotime('2025-02-01')); // 2025
    @endphp

    <div class="header">
        <h1>Promotion Announcement</h1>
        <p>{{ $month }} {{ $year }}</p>
    </div>

    <p class="date">Location: {{ $promotion->employee_branch }}</p>

    <div class="content">
        <p>Dear Mr./Ms. <span class="highlight">{{ $promotion->employee_name }}</span>,</p>

        <p>
            We are pleased to inform you that, as an appreciation of your exceptional performance and dedication,
            you have been promoted to the role of <span class="highlight">{{ $promotion->new_title }}</span>.
        </p>

        <p>
            This promotion is based on the strong recommendations received from your department, branches,
            and the SMC Committee. We recognize your efforts and contributions to the success of our organization.
        </p>

        <p>We look forward to seeing you excel in your new position. Keep up the great work!</p>
    </div>

    <div class="signature">
        <p>Tania Khaddaj</p>
        <p>HR Manager</p>
        <img src="{{ public_path('signatures/tania-signature.png') }}" alt="Tania Khaddaj Signature">
    </div>

    <div class="cc">
        <p><b>CC:</b> Hassan Nasserdine</p>
        <p><b>CC:</b> Malik Barakat</p>
        <p><b>CC:</b> Wael Chamandi</p>
    </div>

    <div class="credits">
        <p>This document was automatically generated by the HR System.</p>
        <p>Developed by <b>Shadi Farhat</b> - IT Manager</p>
    </div>

</body>

</html>
